# Generated by Django 4.0.3 on 2022-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='broker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
